server {

	listen 80;

	server_name localhost;

	location /api/users {
		proxy_pass http://user-service:8084;
	}

	location /api/products {
		
		auth_request /auth;

		auth_request_set $user_id 	$upstream_http_x_user_id;
		auth_request_set $user_role	$upstream_http_x_user_role;

		proxy_set_header X-USER-ID 	$user_id;
		proxy_set_header X-USER-ROLE	$user_role;

		proxy_pass http://product-service:8081;
	}
	
	location /api/orders {
		
		auth_request /auth;

		auth_request_set $user_id 	$upstream_http_x_user_id;

		proxy_set_header X-USER-ID	$user_id;

		proxy_pass http://order-service:8082;
	}

	location = /auth {
		internal;
		proxy_pass http://user-service:8084/api/auth/verify;
	}

}
